{% set name = "v1.6.11" %}
{% set version = "1.6.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f42dc85940d11f3af553551bdd0940a85fff8fa49ceece6e1e969e0279944a1

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=42
    - wheel
    - cython
    - cmake
    - pip
  run:
    - python
    - certifi >=2017.4.17

test:
  imports:
    - uamqp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-uamqp-python
  license: MIT
  license_file:
    - LICENSE
    - src/vendor/azure-uamqp-c/LICENSE
    - src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/LICENSE
    - src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/testtools/testrunner/deps/azure-macro-utils-c/LICENSE
    - src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/testtools/ctest/LICENSE
    - src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/testtools/ctest/deps/azure-macro-utils-c/LICENSE
    - src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/deps/azure-macro-utils-c/LICENSE
    - src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/deps/umock-c/LICENSE
    - src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/deps/umock-c/deps/testrunner/deps/azure-macro-utils-c/LICENSE
    - src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/deps/umock-c/deps/azure-macro-utils-c/LICENSE
    - src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/deps/umock-c/deps/ctest/LICENSE
    - src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/deps/umock-c/deps/ctest/deps/azure-macro-utils-c/LICENSE
    - src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/build_all/packaging/linux/debian/copyright
    - src/vendor/azure-uamqp-c/deps/azure-ctest/LICENSE
    - src/vendor/azure-uamqp-c/deps/azure-ctest/deps/azure-macro-utils-c/LICENSE
    - src/vendor/azure-uamqp-c/deps/azure-macro-utils-c/LICENSE
    - src/vendor/azure-uamqp-c/deps/azure-c-testrunnerswitcher/deps/azure-macro-utils-c/LICENSE
    - src/vendor/azure-uamqp-c/deps/umock-c/LICENSE
    - src/vendor/azure-uamqp-c/deps/umock-c/deps/testrunner/deps/azure-macro-utils-c/LICENSE
    - src/vendor/azure-uamqp-c/deps/umock-c/deps/azure-macro-utils-c/LICENSE
    - src/vendor/azure-uamqp-c/deps/umock-c/deps/ctest/LICENSE
    - src/vendor/azure-uamqp-c/deps/umock-c/deps/ctest/deps/azure-macro-utils-c/LICENSE
    - src/vendor/azure-uamqp-c/build_all/packaging/linux/debian/copyright

extra:
  recipe-maintainers:
    - boldorider4
